name: release

on:
  release:
    types:
      - "published"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Version
        run: |
          filepath="pyfuelprices/_version.py"
          new_version_string="__version__ = \"${{ github.event.release.tag_name }}\""
          sed -i "s/^__version__ = .*$/$new_version_string/" "$filepath"
      - name: Set Build Parameters
        run: |
          filepath="pyfuelprices/build_data.py"
          sed -i "s/^FINELLY_URL=.*$/FINELLY_URL=\"${{ secrets.FINELLY_URL }}\"/" "$filepath"
          sed -i "s/^GASPASS_URL=.*$/GASPASS_URL=\"${{ secrets.GASPASS_URL }}\"/" "$filepath"
      - uses: extractions/setup-just@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build package
        run: just install build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
