"""Python Fuel Prices consts."""

from datetime import timedelta

PROP_FUEL_LOCATION_DYNAMIC_BUILD = "build_on_access"
PROP_FUEL_LOCATION_SOURCE = "source"
PROP_FUEL_LOCATION_SOURCE_ID = "source_id"
PROP_FUEL_LOCATION_PREVENT_CACHE_CLEANUP = "prevent_cache_cleanup"

PROP_AREA_LAT = "lat"
PROP_AREA_LONG = "long"
PROP_AREA_RADIUS = "radius"


ANDROID_USER_AGENT = "Dalvik/2.1.0 (Linux; U; Android 13; Pixel 4 XL Build/TQ3A.230705.001.B4)"
DESKTOP_USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0"

SOURCE_CONFIG_API_KEY = "apikey"

SOURCE_CONFIG_PROXY_ENABLE = "useproxy"
SOURCE_CONFIG_PROXY_HOST = "proxy"
SOURCE_CONFIG_PROXY_PORT = "proxyport"
SOURCE_CONFIG_PROXY_USERNAME = "proxyuser"
SOURCE_CONFIG_PROXY_PASSWORD = "proxypass"
SOURCE_CONFIG_PROXY_PROTOCOL = "proxyproto"

MODULE_CONFIG_PROXY_LIST = "proxylist"
MODULE_CONFIG_ENABLED_SOURCES = "enabled_sources"
MODULE_CONFIG_UPDATE_INTERVAL = "update_interval"
MODULE_CONFIG_COUNTRY_CODE = "country_code"
MODULE_CONFIG_CONFIGURED_AREAS = "areas"
MODULE_CONFIG_TIMEOUT = "timeout"
MODULE_CONFIG_SOURCE_OPTIONS = "source_options"

DEF_MODULE_CONFIG_ENABLED_SOURCES = None
DEF_MODULE_CONFIG_UPDATE_INTERVAL = timedelta(days=1)
DEF_MODULE_CONFIG_CONFIGURED_AREAS = None
DEF_MODULE_CONFIG_TIMEOUT = timedelta(seconds=30)
DEF_MODULE_CONFIG_SOURCE_OPTIONS = {}
DEF_MODULE_CONFIG_COUNTRY_CODE = ""
DEF_MODULE_CONFIG_PROXY_LIST = (
    "https://proxylist.geonode.com"
    "/api/proxy-list?limit=250&page=1&sort_by=lastChecked&sort_type=desc"
)

DEF_MODULE_CONFIG = {
    MODULE_CONFIG_PROXY_LIST: DEF_MODULE_CONFIG_PROXY_LIST,
    MODULE_CONFIG_CONFIGURED_AREAS: DEF_MODULE_CONFIG_CONFIGURED_AREAS,
    MODULE_CONFIG_COUNTRY_CODE: DEF_MODULE_CONFIG_COUNTRY_CODE,
    MODULE_CONFIG_ENABLED_SOURCES: DEF_MODULE_CONFIG_ENABLED_SOURCES,
    MODULE_CONFIG_SOURCE_OPTIONS: DEF_MODULE_CONFIG_SOURCE_OPTIONS,
    MODULE_CONFIG_TIMEOUT: DEF_MODULE_CONFIG_TIMEOUT,
    MODULE_CONFIG_UPDATE_INTERVAL: DEF_MODULE_CONFIG_UPDATE_INTERVAL
}